### ISSUE TITLE
Handle user input output to course information

### ISSUE THREAD

**Issue by ofiralexi** [TechnionYP5779/team1-bot#14] opened 2018-11-21 21:39 UTC
Description:

- [ ] catch user input using dialogflow parameters , and send to server for reply
- [ ] based on the reply given from server , show the user the answer matching to that reply.

relevant API: #177

**Comment by ShaiZeevi** [comment] 2018-12-12 08:07
duplicate of #16

**Closed by ShaiZeevi** 2018-12-12 08:07 UTC
Labels: duplicate
